---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neon-proxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "neon-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "neon-proxy.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.envFrom }}        
          envFrom:
          {{- toYaml .Values.envFrom | nindent 10 }}
        {{- end }}
          env:
          - name: SOLANA_URL 
            value: {{ .Values.solanaUrl }} 
          - name: EVM_LOADER
            value: {{ .Values.EVM_LOADER | squote }}
          - name: CONFIG
            value: {{ .Values.CONFIG | squote  }}
          - name: LOG_FULL_OBJECT_INFO
            value: {{ .Values.indexer.LOG_FULL_OBJECT_INFO | squote }} 
          - name: GATHER_STATISTICS
            value: {{ .Values.indexer.GATHER_STATISTICS | squote }}                                
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: [proxy/run-indexer.sh]
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
