apiVersion: v1
kind: Secret
metadata:
  name: proxy-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  SOLANA_URL: {{ .Values.solanaUrl | b64enc | quote }}
  COMMIT_LEVEL: {{ .Values.commit_level | b64enc | quote }}
  EVM_LOADER: {{ .Values.evm_loader | b64enc | quote }}
  MINIMAL_GAS_PRICE: {{ .Values.minimal_gas_price | toString | b64enc | quote }}
  PERM_ACCOUNT_LIMIT: {{ .Values.perm_account_limit | toString | b64enc | quote }}
  PP_SOLANA_URL: {{ .Values.ppsolanaUrl | b64enc | quote }}
  PROXY_COUNT: {{ .Values.proxyCount | toString | b64enc | quote }}
  KEYS_PER_PROXY: {{ .Values.keysPerProxy | toString | b64enc | quote }}
