version: "3"

services:
  tracer_db:
    container_name: tracer_db
    image: neonlabsorg/neon-accountsdb:v1.13.4-neon-tracer
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_DB: solana
      POSTGRES_USER: solana-user
      POSTGRES_PASSWORD: solana-pass
    hostname: tracer_db
    expose:
      - "5432"
    healthcheck:
      test: [ CMD-SHELL, "pg_isready -h tracer_db -p 5432 -U solana-user" ]
      interval: 5s
      timeout: 10s
      retries: 10


  validator:
    container_name: validator
    image: neonlabsorg/neon-validator:v1.13.4-neon-tracer
    environment:
      SOLANA_URL: http://validator:8899
      RUST_LOG: solana_runtime::system_instruction_processor=trace,solana_runtime::message_processor=error,solana_bpf_loader=debug,solana_rbpf=debug,neon_dumper_plugin::postgres_client=debug
      GEYSER_PLUGIN_CONFIG: /opt/accountsdb-plugin-config.json
    hostname: validator
    expose:
      - "8899"
      - "9900"
      - "8900"
      - "8001"
      - "8001-8009/udp"
    healthcheck:
      # Must be available from outside (calling without -u causes premature result)
      test: [ CMD-SHELL, "./wait-for-neon.sh" ]
      interval: 5s
      timeout: 5s
      retries: 200
    entrypoint: /opt/solana/bin/solana-run-neon.sh
    ports:
      - 127.0.0.1:8899:8899
    volumes:
      - ./accountsdb-plugin-config.json:/opt/accountsdb-plugin-config.json


  neon-tracer:
    container_name: neon-tracer
    hostname: neon-tracer
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: neon=debug,metrics=debug
      LISTEN_ADDR: 0.0.0.0:8250
      SOLANA_URL: http://validator:8899
      EVM_LOADER: 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io
      TRACER_DB_HOST: tracer_db
      TRACER_DB_PORT: 5432
      TRACER_DB_NAME: solana
      TRACER_DB_USER: solana-user
      TRACER_DB_PASSWORD: solana-pass
      INDEXER_DB_HOST: postgres
      INDEXER_DB_PORT: 5432
      INDEXER_DB_NAME: neon-db
      INDEXER_DB_USER: neon-proxy
      INDEXER_DB_PASSWORD: neon-proxy-pass
      WEB3_PROXY: http://proxy:9090/solana
      METRICS_IP: 0.0.0.0
      METRICS_PORT: 9292
      NEON_TOKEN_MINT: HPsV9Deocecw3GeZv1FkAPNCBRfuVyfw9MMwjwRe1xaU
      NEON_CHAIN_ID: 111
      MONITORING_INTERVAL_SEC: 15
    image: neonlabsorg/neon-tracer:${BUILDKITE_COMMIT:-ci-eip-1898}
    expose:
      - "8250"
    ports:
      - "127.0.0.1:8250:8250"
      - "127.0.0.1:9292:9292"

  neon-rpc:
    container_name: neon-rpc
    hostname: neon-rpc
    image: neonlabsorg/neon-rpc:${BUILDKITE_COMMIT:-ci-eip-1898}
    expose:
      - "9090"
    ports:
      - 127.0.0.1:9090:9090



