{{- if .Values.postgres.enabled -}}
{{- if eq .Values.persistence.storageClassName "efs" -}}
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.efsDriver.name }}
  namespace: {{ .Release.Namespace }}
spec:
  attachRequired: false
{{- end -}}
{{- end -}}


{{- if .Values.postgres.enabled -}}
{{- if eq .Values.persistence.storageClassName "scw-bssd" -}}
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.efsDriver.name }}
  namespace: {{ .Release.Namespace }}
spec:
  attachRequired: false
{{- end -}}
{{- end -}}

