{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Namespace }}-postgres-persistent-volume
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  {{- if eq .Values.persistence.storageClass "host" }}
  hostPath:
    path: "{{ .Values.persistence.hostPath }}/{{ .Release.Namespace }}/"
  {{- end -}}
  {{- if eq .Values.persistence.storageClass "efs" }}
  csi:
    driver: {{ .Values.fsDriver.name }}
    volumeHandle: {{ .Values.fsDriver.fsId }}
  {{- end -}}
  {{- if eq .Values.persistence.storageClass "pd" }}
  csi:
    driver: {{ .Values.persistence.fsDriver.name }}
    fsType: ext4
    volumeHandle: {{ .Values.persistence.fsDriver.fsId }}
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1660085000920-8081-pd.csi.storage.gke.io    
  {{- end -}}
  {{- if eq .Values.persistence.storageClass "scw-bssd" }}
  csi:
    driver: {{ .Values.fsDriver.name }}
    volumeHandle: {{ .Values.fsDriver.fsId }}
  {{- end -}}  
{{- end }}
