{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-postgres-volume-claim
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- if eq .Values.persistence.storageClass "standard" }}  
  accessModes:
    - ReadWriteMany
  {{- end }}
  {{- if eq .Values.persistence.storageClass "efs" }}   
  accessModes:
    - ReadWriteMany
  {{- end }}
   {{- if eq .Values.persistence.storageClass "pd" }}  
  accessModes:
    - ReadWriteOnce
  {{- end }}     
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}       