apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if empty .Values.postgres.password }}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace "postgres-secret") }}
  {{- if $secret }}
  POSTGRES_PASSWORD: {{ $secret.data.POSTGRES_PASSWORD }}
  {{- else }}
  POSTGRES_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end}}
  {{- else }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  {{- end}}
  POSTGRES_DB: {{ .Values.postgres.dbName | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | b64enc | quote }}
  POSTGRES_HOST: {{ .Values.postgres.host | b64enc | quote }}
  POSTGRES_PORT: {{ .Values.service.port | toString | b64enc }}
  POSTGRES_SSL: {{ .Values.postgres.ssl | b64enc | quote }}
