apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: neon-proxy
  labels: 
    app: busybox
spec:
  serviceAccountName: neon-proxy-sa
  containers:
  - name: bash
    image: bash
    command: ["/bin/sh", "-ec", sleep 3600""]