apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: neon-proxy
    meta.helm.sh/release-namespace: neon-proxy
  name: neon-proxy-svc-node-port
  namespace: neon-proxy
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: neon-proxy
    app.kubernetes.io/name: neon-proxy
  
  sessionAffinity: ClientIP

  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30007
